// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITIDbEFCorePowerTool.Models
{
    public partial class Department
    {
        public Department()
        {
            Instructors = new HashSet<Instructor>();
        }

        [Key]
        public int Dept_Id { get; set; }
        [StringLength(50)]
        public string Dept_Name { get; set; }
        [StringLength(100)]
        public string Dept_Desc { get; set; }
        [StringLength(50)]
        public string Dept_Location { get; set; }
        public int? Dept_Manager { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Manager_hiredate { get; set; }

        [ForeignKey(nameof(Dept_Manager))]
        [InverseProperty(nameof(Instructor.Departments))]
        public virtual Instructor Dept_ManagerNavigation { get; set; }
        [InverseProperty(nameof(Instructor.Dept_))]
        public virtual ICollection<Instructor> Instructors { get; set; }
    }
}