// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITIDbEFCorePowerTool.Models
{
    public partial class Instructor
    {
        public Instructor()
        {
            Departments = new HashSet<Department>();
        }

        [Key]
        public int Ins_Id { get; set; }
        [StringLength(50)]
        public string Ins_Name { get; set; }
        [StringLength(50)]
        public string Ins_Degree { get; set; }
        [Column(TypeName = "money")]
        public decimal? Salary { get; set; }
        public int? Dept_Id { get; set; }

        [ForeignKey(nameof(Dept_Id))]
        [InverseProperty(nameof(Department.Instructors))]
        public virtual Department Dept_ { get; set; }
        [InverseProperty(nameof(Department.Dept_ManagerNavigation))]
        public virtual ICollection<Department> Departments { get; set; }
    }
}