// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ITIDbEFCorePowerTool.Models;

namespace ITIDbEFCorePowerTool.Data
{
    public partial class ITIContext : DbContext
    {
        public ITIContext()
        {
        }

        public ITIContext(DbContextOptions<ITIContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Instructor> Instructor { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Department>(entity =>
            {
                entity.Property(e => e.Dept_Id).ValueGeneratedNever();

                entity.HasOne(d => d.Dept_ManagerNavigation)
                    .WithMany(p => p.Departments)
                    .HasForeignKey(d => d.Dept_Manager)
                    .HasConstraintName("FK_Department_Instructor");
            });

            modelBuilder.Entity<Instructor>(entity =>
            {
                entity.Property(e => e.Ins_Id).ValueGeneratedNever();

                entity.HasOne(d => d.Dept_)
                    .WithMany(p => p.Instructors)
                    .HasForeignKey(d => d.Dept_Id)
                    .HasConstraintName("FK_Instructor_Department");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}