//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public int Ins_Id { get; set; }
        public string Ins_Name { get; set; }
        public string Ins_Degree { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Dept_Id { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
